Logo 파트 한글 번역 완료
sij411/the-art-of-code-kor pull request #7
Opened 2024-05-10 12:01 UTC by leehyewon0531

짧은데 은근 어렵네요....!? 흑흑 ㅋ
어색한 부분이 잇으면 신랄하게 비판해주세요 ... 🔥🔥🔥🔥

2024-05-11 11:14 UTC, sij411 commented on 02-logo.md
> +이 자리에 있을 수 있을 만큼 지혜로운 몇몇의 사람들을 위해 컨퍼런스를 마무리해 달라고요. 왜냐하면 여기서는
**이 자리에 참석할 만큼 ~~있을 만큼~~ 현명한**
- 이런 느낌의 해석도 한번 고려해주세요.

2024-05-11 11:54 UTC, leehyewon0531 commented on 02-logo.md
> +이 자리에 있을 수 있을 만큼 지혜로운 몇몇의 사람들을 위해 컨퍼런스를 마무리해 달라고요. 왜냐하면 여기서는
오!! 훨씬 매끄럽고 좋은 것 같아요 🫡🫡🫡 수정하겠습니다!!!

2024-05-11 12:09 UTC, sij411 requested changes
굿굿!! 리뷰 남긴것들만 한번 참고해주세요. 전 걍 한국어로 다시 읽어봤을 때 부자연스러운건 의역해서 고치고 바로 이해되지 않는 단어는 idiom이거나 영국 특유의 말투일 수 있어서 구글링하는 편 ㅋㅋ 말투만 들어서는 영국인인 것 같은데 확실친 않음 ㅎ핳

2024-05-11 12:09 UTC, sij411 commented on 02-logo.md
> +제가 The art of code(코드의 예술)라고 부르는 것에 대해 여러분에게 이야기하면서 강력한 경쟁이 벌어지고 있기 때문이죠. 그런데,
(위 문장이랑 이어짐) 왜냐하면 여기 이 자리에 치열한 경쟁이 있었기 때문이죠. 제가 코드의 예술이라고 부르는 것에 대해 이야기하면서 말이에요. 

- 이렇게 번역해본 이유는 컨퍼런스에서 강연자가 말할 때 in this spot. 하고 뜸을 들이고 By talking to you로 이어졌기 때문입니다 ㅎㅎ. 그냥 참고!

2024-05-11 12:09 UTC, sij411 commented on 02-logo.md
> +여기 짧은 소개 부분에 쓰여진 언어를 알아차리신 분이 계신가요? (대답을 듣고) 로고.
- intro sequence -> 한국어로 그냥 인트로 시퀀스, 오프닝 시퀀스, 타이틀 시퀀스라고 사용하더라고요. 처음 알았음.

2024-05-13 06:02 UTC, leehyewon0531 commented on 02-logo.md
> +제가 The art of code(코드의 예술)라고 부르는 것에 대해 여러분에게 이야기하면서 강력한 경쟁이 벌어지고 있기 때문이죠. 그런데,
앗 영상 다시 보니 그런 것 같네요!? 어쩐지 뭔가 이해가 안되더라 ㅠㅠㅠ 감사합니다!!

2024-05-13 06:04 UTC, leehyewon0531 commented on 02-logo.md
> +여기 짧은 소개 부분에 쓰여진 언어를 알아차리신 분이 계신가요? (대답을 듣고) 로고.
헐 저도 처음 알았어요,,, 영화 쪽에서 자주 쓰는 표현 같네요?! 수정하겠습니다!!!ㅎㅎㅎㅎ

2024-05-13 06:06 UTC, merged