Amstrad 파트 한글 번역 완료
sij411/the-art-of-code-kor pull request #9
Opened 2024-05-11 11:56 UTC by leehyewon0531

느낌적인 느낌으로 너무 의역을 많이 했나 싶기도,,,
BBS는 Bulletin Board System의 약자로 그냥 게시판 시스템을 BBS로 부르는 것 같아서 그대로 썼어요...! (저는 처음 알았다는..)

2024-05-14 06:42 UTC, sij411 requested changes
감사합니다 ~~~
저도 수요일부터 다시 작업하겠습니다 하하

2024-05-14 06:42 UTC, sij411 commented on 03-amstrad.md
> +이걸 가지고 할 수 있는 게 별로 없어요. 통신도 못 하고, 전화도 못 하고, BBS나 게시판, 인터넷도 없어요. 하지만 이 로고 프로그래밍 언어에 있는 게 가지고 있는 건 뭘까요?
1. 없어요 -> 없었어요. 

- 굳이 따지자면 하핳
- 모뎀 없다는게 통신이 없단 뜻이구나 아하
2.  질문이 아닌 것 같습니다. 그러면 what did it have ~ ? 였지 않을까요?
- 하지만 그것 (컴퓨터)이 진정 가지고 있었던 것은 이 로고 프로그래밍 언어였습니다.

2024-05-14 06:42 UTC, sij411 commented on 03-amstrad.md
> +되돌아가서 다른 것을 시도해 보곤 했습니다. 제 경력 전반에 걸쳐 저를 짜릿하게 했던, 소프트웨어와 디자인 시스템들을 개발한 사실은
developing software and designing system 
- 소프트웨어를 개발하고 시스템을 설계하고
- 이런 해석은 어떠신가용

2024-05-14 06:42 UTC, sij411 commented on 03-amstrad.md
> +나쁜 하루를 보냈든 간에, 여러분들이 여전히 (의역) 테스트를 다 통과했을 때나
ㅋㅋㅋㅋ 테스트 다 통과하면 초록색 뜨는거 말하는듯 ㅋㅋㅋㅋㅋ

2024-05-14 06:42 UTC, sij411 commented on 03-amstrad.md
> +어떤 유용한 것도 얘기하지 않을 거예요. 왜냐하면 저는 예술에 대해 말할 것이고, 오스카 와일드는 "모든 예술은 전혀 쓸모가 없다."라고 했기 때문이죠.
전혀 보다는 꽤 같이 좀 더 강도가 낮은 단어가 어떨까요?

2024-05-16 14:58 UTC, leehyewon0531 commented on 03-amstrad.md
> +이걸 가지고 할 수 있는 게 별로 없어요. 통신도 못 하고, 전화도 못 하고, BBS나 게시판, 인터넷도 없어요. 하지만 이 로고 프로그래밍 언어에 있는 게 가지고 있는 건 뭘까요?
모뎀이 전화 신호 전달을 위한 변조기-복조기 느낌이길래 약간 의역?해 본 건데 직역하는 게 나앗을라나요 ㄷㄷ
1, 2번은 코멘트 주신 게 맞는 것 같아서 수정하겠습니다!!!>< 감사합니다 ㅎㅎㅎ

2024-05-16 14:59 UTC, leehyewon0531 commented on 03-amstrad.md
> +되돌아가서 다른 것을 시도해 보곤 했습니다. 제 경력 전반에 걸쳐 저를 짜릿하게 했던, 소프트웨어와 디자인 시스템들을 개발한 사실은
아 좋은 것 같습니다!!!! 뭔가 "디자인 시스템"이라는 용어가 익숙해서 이렇게 생각해버린 것 같네요 ㄷㄷ 감사합니다!!!

2024-05-16 15:00 UTC, leehyewon0531 commented on 03-amstrad.md
> +나쁜 하루를 보냈든 간에, 여러분들이 여전히 (의역) 테스트를 다 통과했을 때나
ㅋㅋㅋㅋㅋㅋㅋ맞는 거 같아욬!!! 올 그린 ^^ 👍

2024-05-16 15:01 UTC, leehyewon0531 commented on 03-amstrad.md
> +어떤 유용한 것도 얘기하지 않을 거예요. 왜냐하면 저는 예술에 대해 말할 것이고, 오스카 와일드는 "모든 예술은 전혀 쓸모가 없다."라고 했기 때문이죠.
저도 첨에 그렇게 쓸까 했는데 오스카 와일드의 이 명언을 이상하게 한국에서 다 "모든 예술은 전적으로 무용하다", "모든 예술은 정말이지 쓸모없다" 이런 식으로 해석하더라고요...?! 왜 그런진 모르겠지만 ㅠㅠ 헷갈립니다 😢😢😢

2024-05-18 04:59 UTC, merged